# .meshrc.yaml  
sources:
  - name: Database
    handler:
      mysql:
        host: localhost
        port: 3306
        user: root
        password: '12345678'
        database: ajkecommerce
        typeCast: true
        supportBigNumbers: true
        bigNumberStrings: false
        typeMapping:
          tinyint: 'Boolean'

transforms:
  - namingConvention:
      mode: wrap
      fieldNames: camelCase
      typeNames: pascalCase

additionalTypeDefs: |
  scalar DateTime
  scalar Timestamp