# .meshrc.yaml - Configuración optimizada para generar solo tipos básicos
sources:
  - name: Database
    handler:
      mysql:
        host: localhost
        port: 3306
        user: root
        password: '12345678'
        database: ajkecommerce
        typeCast: true
        supportBigNumbers: true
        bigNumberStrings: false

        tableColumnTypesMap:
          # Esto ayuda a Mesh a entender mejor los tipos
          '*_id': 'Int'
          'created_at': 'Timestamp'
          'updated_at': 'Timestamp'

transforms:
  - namingConvention:
      mode: wrap
      fieldNames: camelCase
      typeNames: pascalCase

additionalTypeDefs: |
  scalar DateTime
  scalar Timestamp
