
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.9.0
 * Query Engine version: 81e4af48011447c3cc503a190e86995b66d2a28e
 */
Prisma.prismaVersion = {
  client: "6.9.0",
  engine: "81e4af48011447c3cc503a190e86995b66d2a28e"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.Attribute_option_imagesScalarFieldEnum = {
  id: 'id',
  attribute_option_id: 'attribute_option_id',
  image_type: 'image_type',
  display_order: 'display_order',
  image_url_thumb: 'image_url_thumb',
  image_url_normal: 'image_url_normal',
  image_url_zoom: 'image_url_zoom',
  alt_text: 'alt_text',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Attribute_optionsScalarFieldEnum = {
  id: 'id',
  attribute_id: 'attribute_id',
  value: 'value',
  additional_cost: 'additional_cost'
};

exports.Prisma.AttributesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  display_type: 'display_type'
};

exports.Prisma.BannerScalarFieldEnum = {
  id: 'id',
  title: 'title',
  subtitle: 'subtitle',
  description: 'description',
  created_at: 'created_at',
  updated_at: 'updated_at',
  display_order: 'display_order',
  link: 'link',
  image_url: 'image_url'
};

exports.Prisma.BrandsScalarFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.CategoriesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  parent_id: 'parent_id',
  image_url: 'image_url'
};

exports.Prisma.CustomersScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  password: 'password',
  address_id: 'address_id',
  is_active: 'is_active',
  created_at: 'created_at',
  updated_at: 'updated_at',
  lastname: 'lastname',
  photo: 'photo',
  name: 'name'
};

exports.Prisma.Customers_addressesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  id_customer: 'id_customer',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.PermissionsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Product_categoriesScalarFieldEnum = {
  product_id: 'product_id',
  category_id: 'category_id'
};

exports.Prisma.Product_variantsScalarFieldEnum = {
  id: 'id',
  product_id: 'product_id',
  sku: 'sku',
  price: 'price',
  stock: 'stock',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.ProductsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  brand_id: 'brand_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  base_price: 'base_price'
};

exports.Prisma.Promotion_variantsScalarFieldEnum = {
  promotion_id: 'promotion_id',
  variant_id: 'variant_id',
  promotion_price: 'promotion_price',
  stock_limit: 'stock_limit',
  created_at: 'created_at'
};

exports.Prisma.PromotionsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  start_date: 'start_date',
  end_date: 'end_date',
  discount_type: 'discount_type',
  discount_value: 'discount_value',
  min_purchase_amount: 'min_purchase_amount',
  is_active: 'is_active',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Rating_imagesScalarFieldEnum = {
  id: 'id',
  rating_id: 'rating_id',
  image_url: 'image_url',
  created_at: 'created_at'
};

exports.Prisma.RolesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Roles_sectionsScalarFieldEnum = {
  id: 'id',
  id_section: 'id_section',
  id_rol: 'id_rol'
};

exports.Prisma.SectionsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  url: 'url',
  image: 'image',
  display_order: 'display_order'
};

exports.Prisma.ServicesScalarFieldEnum = {
  id: 'id',
  title: 'title',
  subtitle: 'subtitle',
  image_url: 'image_url',
  slug: 'slug',
  description: 'description',
  created_at: 'created_at',
  updated_at: 'updated_at',
  display_order: 'display_order'
};

exports.Prisma.Services_imagesScalarFieldEnum = {
  id: 'id',
  title: 'title',
  subtitle: 'subtitle',
  description: 'description',
  created_at: 'created_at',
  updated_at: 'updated_at',
  display_order: 'display_order',
  id_service: 'id_service',
  image_url: 'image_url'
};

exports.Prisma.UsersScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  password: 'password',
  role_id: 'role_id',
  is_active: 'is_active',
  created_at: 'created_at',
  updated_at: 'updated_at',
  lastname: 'lastname',
  photo: 'photo'
};

exports.Prisma.Variant_attribute_optionsScalarFieldEnum = {
  variant_id: 'variant_id',
  attribute_option_id: 'attribute_option_id'
};

exports.Prisma.Variant_imagesScalarFieldEnum = {
  id: 'id',
  variant_id: 'variant_id',
  image_type: 'image_type',
  image_url_thumb: 'image_url_thumb',
  image_url_normal: 'image_url_normal',
  image_url_zoom: 'image_url_zoom',
  is_primary: 'is_primary',
  display_order: 'display_order',
  alt_text: 'alt_text',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Variant_ratingsScalarFieldEnum = {
  id: 'id',
  variant_id: 'variant_id',
  customer_id: 'customer_id',
  rating: 'rating',
  review: 'review',
  title: 'title',
  verified_purchase: 'verified_purchase',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.attribute_option_imagesOrderByRelevanceFieldEnum = {
  image_url_thumb: 'image_url_thumb',
  image_url_normal: 'image_url_normal',
  image_url_zoom: 'image_url_zoom',
  alt_text: 'alt_text'
};

exports.Prisma.attribute_optionsOrderByRelevanceFieldEnum = {
  value: 'value'
};

exports.Prisma.attributesOrderByRelevanceFieldEnum = {
  name: 'name'
};

exports.Prisma.bannerOrderByRelevanceFieldEnum = {
  title: 'title',
  subtitle: 'subtitle',
  description: 'description',
  link: 'link',
  image_url: 'image_url'
};

exports.Prisma.brandsOrderByRelevanceFieldEnum = {
  name: 'name'
};

exports.Prisma.categoriesOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description',
  image_url: 'image_url'
};

exports.Prisma.customersOrderByRelevanceFieldEnum = {
  username: 'username',
  email: 'email',
  password: 'password',
  lastname: 'lastname',
  photo: 'photo',
  name: 'name'
};

exports.Prisma.customers_addressesOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description'
};

exports.Prisma.permissionsOrderByRelevanceFieldEnum = {
  name: 'name'
};

exports.Prisma.product_variantsOrderByRelevanceFieldEnum = {
  sku: 'sku'
};

exports.Prisma.productsOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description'
};

exports.Prisma.promotionsOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description'
};

exports.Prisma.rating_imagesOrderByRelevanceFieldEnum = {
  image_url: 'image_url'
};

exports.Prisma.rolesOrderByRelevanceFieldEnum = {
  name: 'name'
};

exports.Prisma.sectionsOrderByRelevanceFieldEnum = {
  name: 'name',
  url: 'url',
  image: 'image'
};

exports.Prisma.servicesOrderByRelevanceFieldEnum = {
  title: 'title',
  subtitle: 'subtitle',
  image_url: 'image_url',
  slug: 'slug',
  description: 'description'
};

exports.Prisma.services_imagesOrderByRelevanceFieldEnum = {
  title: 'title',
  subtitle: 'subtitle',
  description: 'description',
  image_url: 'image_url'
};

exports.Prisma.usersOrderByRelevanceFieldEnum = {
  username: 'username',
  email: 'email',
  password: 'password',
  lastname: 'lastname',
  photo: 'photo'
};

exports.Prisma.variant_imagesOrderByRelevanceFieldEnum = {
  image_url_thumb: 'image_url_thumb',
  image_url_normal: 'image_url_normal',
  image_url_zoom: 'image_url_zoom',
  alt_text: 'alt_text'
};

exports.Prisma.variant_ratingsOrderByRelevanceFieldEnum = {
  review: 'review',
  title: 'title'
};
exports.attribute_option_images_image_type = exports.$Enums.attribute_option_images_image_type = {
  front: 'front',
  back: 'back',
  left: 'left',
  right: 'right',
  top: 'top',
  bottom: 'bottom',
  detail: 'detail',
  lifestyle: 'lifestyle',
  packaging: 'packaging'
};

exports.attributes_display_type = exports.$Enums.attributes_display_type = {
  radio: 'radio',
  pills: 'pills',
  select: 'select',
  color: 'color',
  custom: 'custom'
};

exports.promotions_discount_type = exports.$Enums.promotions_discount_type = {
  percentage: 'percentage',
  fixed_amount: 'fixed_amount'
};

exports.variant_images_image_type = exports.$Enums.variant_images_image_type = {
  front: 'front',
  back: 'back',
  left: 'left',
  right: 'right',
  top: 'top',
  bottom: 'bottom',
  detail: 'detail',
  lifestyle: 'lifestyle',
  packaging: 'packaging'
};

exports.Prisma.ModelName = {
  attribute_option_images: 'attribute_option_images',
  attribute_options: 'attribute_options',
  attributes: 'attributes',
  banner: 'banner',
  brands: 'brands',
  categories: 'categories',
  customers: 'customers',
  customers_addresses: 'customers_addresses',
  permissions: 'permissions',
  product_categories: 'product_categories',
  product_variants: 'product_variants',
  products: 'products',
  promotion_variants: 'promotion_variants',
  promotions: 'promotions',
  rating_images: 'rating_images',
  roles: 'roles',
  roles_sections: 'roles_sections',
  sections: 'sections',
  services: 'services',
  services_images: 'services_images',
  users: 'users',
  variant_attribute_options: 'variant_attribute_options',
  variant_images: 'variant_images',
  variant_ratings: 'variant_ratings'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
